/**
 * UI strings, one dictionary per language.
 *
 * `t` is the dictionary for the active country's language (COUNTRY.language).
 * Strings that carry values are small functions. Text that names the country
 * or an admin level reads it from COUNTRY, so a new country with an existing
 * language needs no new strings.
 *
 * `nl` is the reference: `it` must have exactly the same shape (`Strings`).
 * Data keys (GeoJSON properties, the ma..zo opening-hours keys, carrier
 * `source.method` values) stay as they are; only what is displayed lives here.
 */

import { COUNTRY } from '@/config/country';

type SourceMethod = 'Publieke API' | 'Web scraping' | 'Browser-automatisering';

const nl = {
  common: {
    loading: 'Laden...',
    mapLoading: 'Kaart laden...',
    municipalityLoading: 'Gemeente laden...',
    close: 'Sluiten',
    unknown: 'Onbekend',
    unknownLower: 'onbekend',
    points: 'Pakketpunten',
    updated: (date: string) => `Update: ${date}`,
  },

  meta: {
    title: `${COUNTRY.siteName} - Alle pakketpunten in ${COUNTRY.name} op de kaart`,
    description: (carriers: string) =>
      `Bekijk en vergelijk alle pakketpunten en pakketautomaten in ${COUNTRY.name}. ${carriers} op een interactieve kaart per gemeente.`,
    ogTitle: `${COUNTRY.siteName} - Alle pakketpunten in ${COUNTRY.name}`,
    ogDescription: (carrierCount: number) =>
      `Bekijk en vergelijk alle pakketpunten en pakketautomaten in ${COUNTRY.name} van ${carrierCount} vervoerders op een interactieve kaart per gemeente.`,
  },

  categories: {
    locker: 'Pakketautomaat',
    shop: 'Pakketpunt',
  },

  days: {
    long: {
      ma: 'Maandag',
      di: 'Dinsdag',
      wo: 'Woensdag',
      do: 'Donderdag',
      vr: 'Vrijdag',
      za: 'Zaterdag',
      zo: 'Zondag',
    },
    short: {
      ma: 'Ma',
      di: 'Di',
      wo: 'Wo',
      do: 'Do',
      vr: 'Vr',
      za: 'Za',
      zo: 'Zo',
    },
  },

  header: {
    appTitle: 'Pakketpunten',
    nearestTitle: 'Dichtstbijzijnde pakketpunten zoeken',
    nearestTitleWithAddress: (address: string) => `Dichtstbijzijnde pakketpunten bij "${address}"`,
    data: 'Data',
    api: 'API',
    share: 'Delen',
    about: 'Over',
    openMenu: 'Menu openen',
    findNearest: 'Dichtstbijzijnde zoeken',
    apiDocs: 'API Documentatie',
    shareEmbed: 'Delen / Embed',
    aboutProject: 'Over dit project',
    sidebarTitle: 'Filters & Stats',
    openFilters: 'Filters openen',
    dataSourcesInfo: 'Info over databronnen',
  },

  filters: {
    title: 'Filters',
    carriers: 'Vervoerders',
    locationType: 'Type locatie',
    service: 'Service',
    pickup: 'Ophalen',
    pickupDescription: 'Pakket ophalen',
    dropoff: 'Verzenden',
    dropoffDescription: 'Pakket versturen',
    serviceHint: 'Ophalen = pakket ontvangen, Verzenden = pakket versturen',
    locations: 'Locaties',
    allLocations: 'Alle locaties',
    sharedAddresses: 'Gedeelde adressen',
    sharedAddressesHint: 'Adressen met meerdere vervoerders',
    markerStyle: 'Markering weergave',
    logoIcons: 'Logo iconen',
    coloredDots: 'Gekleurde stippen',
    coverage: 'Dekkingsgebieden',
    buffer300: '300m buffer lijn',
    buffer400: '400m buffer lijn',
    bufferFill: 'Buffer opvulling',
    mergedBuffers: 'Samengevoegde buffers',
    mergedBuffersTip: 'Als het laden van pakketpunten traag is, schakel deze instelling uit.',
    boundary: 'Gemeentegrens',
    loadingProgress: (loaded: number, total: number) => `Laden: ${loaded}/${total}`,
    loadingParen: '(laden...)',
    reset: 'Reset Filters',
  },

  stats: {
    municipalitiesCount: (count: number) => `${count} gemeentes`,
    points: 'Pakketpunten',
    occupancy: 'Bezetting',
  },

  map: {
    noPointsTitle: 'Geen pakketpunten gevonden',
    noPointsBody: 'Deze gemeente heeft momenteel geen pakketpunten in onze database. De kaart toont wel de gemeentegrens.',
  },

  popup: {
    openingHours: 'Openingstijden:',
    closed: 'gesloten',
    carrier: 'Vervoerder:',
    type: 'Type:',
    services: 'Services:',
    pickup: '↓ Ophalen',
    dropoff: '↑ Verzenden',
    showRawData: 'Toon Ruwe Data',
    streetView: 'Bekijk in Street View',
    searchLocation: 'Uw zoeklocatie',
  },

  nearest: {
    title: 'Dichtstbijzijnde pakketpunten',
    placeholder: 'Adres of postcode...',
    locating: 'Locatie ophalen…',
    useMyLocation: 'Gebruik mijn locatie',
    myLocation: 'Mijn locatie',
    openingHours: 'Openingstijden',
    modeAll: 'Alle',
    modeNow: 'Nu open',
    modeCustom: 'Op tijdstip',
    includeUnknownHours: 'Toon ook punten zonder bekende openingstijden',
    noneWithinRadius: 'Geen pakketpunten binnen 500m gevonden',
    noneOpenWithinRadius: 'Geen pakketpunten binnen 500m op dit tijdstip open',
    closedCount: (count: number) => `${count} gesloten`,
    withoutHoursCount: (count: number) => `${count} zonder openingstijden`,
    withoutHoursExcluded: (count: number) => `${count} zonder openingstijden uitgesloten`,
    resultsWithinRadius: (count: number) => `${count} pakketpunt${count !== 1 ? 'en' : ''} binnen 500m`,
    nowOpenSuffix: ' · nu open',
    openAtSuffix: (day: string, time: string) => ` · open op ${day} ${time}`,
    helpText:
      'Voer een adres of postcode in. De kaart schakelt automatisch naar de juiste gemeente en toont de 10 dichtstbijzijnde pakketpunten.',
    searchFailed: 'Adres zoeken mislukt',
    lookupFailed: 'Adres ophalen mislukt',
    addressOutsideCountry: `Dit adres ligt niet in een gemeente in ${COUNTRY.name}`,
    noCoordinates: 'Geen coordinaten beschikbaar',
    municipalityNotInDb: (name: string) => `Gemeente "${name}" niet in database`,
    noResults: 'Geen resultaten gevonden',
    geolocationUnsupported: 'Locatie wordt niet ondersteund door deze browser',
    noMunicipalityAtLocation: `Geen gemeente in ${COUNTRY.name} bij deze locatie gevonden`,
    reverseGeocodeFailed: 'Locatie kon niet worden omgezet naar een adres',
    permissionDenied: 'Locatie geweigerd. Schakel locatietoegang in voor deze site.',
    positionUnavailable: 'Locatie is op dit moment niet beschikbaar',
    timeout: 'Locatie ophalen duurde te lang',
    locateFailed: 'Locatie ophalen mislukt',
  },

  search: {
    placeholder: 'Zoek adres...',
    searchFailed: 'Adres zoeken mislukt. Probeer het opnieuw.',
    lookupFailed: 'Adres ophalen mislukt. Probeer het opnieuw.',
    addressOutsideCountry: `Dit adres ligt niet in een gemeente in ${COUNTRY.name}`,
    noCoordinates: 'Geen coördinaten beschikbaar voor dit adres',
    municipalityNotAvailable: (name: string) => `Gemeente "${name}" niet beschikbaar in de database`,
    noResultsFor: (query: string) => `Geen resultaten voor "${query}"`,
    typeAddress: 'Adres',
    typeStreet: 'Straat',
    typePostcode: 'PC',
    typePlace: 'Plaats',
  },

  selector: {
    placeholder: 'Selecteer gemeente...',
    count: (count: number) => `${count} gemeentes`,
    sortAsc: 'Sorteer A-Z',
    sortDesc: 'Sorteer Z-A',
    noMatches: (term: string) => `Geen gemeentes gevonden voor "${term}"`,
    nationalOverview: 'Landelijk overzicht',
  },

  share: {
    title: 'Delen',
    directLink: (name: string) => `Directe link naar ${name}`,
    copy: 'Kopieer',
    copied: 'Gekopieerd!',
    embedCode: 'Embed code',
    embedHint: (name: string) => `Plak deze code op je website om de kaart van ${name} in te sluiten.`,
    width: 'Breedte',
    height: 'Hoogte',
    preview: 'Voorbeeld',
    iframeTitle: (name: string) => `Pakketpunten ${name}`,
  },

  about: {
    title: 'Over dit project',
    tabAbout: 'Over',
    tabSources: 'Bronnen',
    tabUsage: 'Gebruik',
    tabLinks: 'Links',
    intro: `Een interactief visualisatieplatform voor pakketpuntlocaties in ${COUNTRY.name}. Dit project verzamelt publieke data van meerdere vervoerders en toont deze op een overzichtelijke kaart met filteropties en statistieken.`,
    audience:
      'De viewer ondersteunt gemeenten, onderzoekers en beleidsmakers bij het analyseren van de dekkingsgraad van pakketpunten over de gemeenten en het identificeren van onderbedeelde gebieden om nieuwe plaatsingen van pakketpunten mogelijk te maken.',
    featuresTitle: 'Features',
    featureMap: `Interactieve kaart met alle gemeenten in ${COUNTRY.name}`,
    featureFiltering: 'Real-time filtering op vervoerder en locatie',
    featureCoverage: 'Dekkingsgebied visualisatie (300m en 400m buffers)',
    featureStats: 'Statistieken per gemeente en vervoerder',
    featureResponsive: 'Responsive design voor desktop en mobiel',
    featureExport: 'Export functionaliteit voor data-analyse',
    ackTitle: 'Dankbetuiging',
    ackDerivedFrom: 'Deze viewer is afgeleid van',
    ackJoin: ' en ',
    ackMiddle: ', oorspronkelijk een concept van en in samenwerking met de ',
    ackOrg: 'Gemeente Zwolle',
    ackEnd: ', waarvoor dank!',
    openSourceTitle: 'Open Source',
    openSourceBody:
      'Dit project is open source en beschikbaar onder de MIT-licentie. Voor technische documentatie, broncode en contributie mogelijkheden:',
    githubRepo: 'GitHub Repository',
    sourcesTitle: 'Data Bronnen',
    sourcesIntro:
      "Locatiegegevens worden verzameld van publieke API's en websites van de betreffende vervoerders zonder authenticatie vereisten.",
    methods: {
      'Publieke API': 'Publieke API',
      'Web scraping': 'Web scraping',
      'Browser-automatisering': 'Browser-automatisering',
    } satisfies Record<SourceMethod, string>,
    missingTitle: 'Niet (volledig) opgenomen',
    missingIntro: `Deze netwerken zijn in ${COUNTRY.name} moeilijk of niet te verkrijgen zonder account of sleutel:`,
    additionalSourcesTitle: 'Aanvullende Bronnen',
    addressSearchLabel: 'Adreszoeken:',
    boundariesLabel: 'Gemeentegrenzen:',
    boundariesSource: `OpenStreetMap (${COUNTRY.municipalityCodeLabel}-codes)`,
    basemapLabel: 'Kaartachtergrond:',
    basemapSource: 'OpenStreetMap tiles',
    updateFrequencyTitle: 'Update Frequentie',
    updateFrequencyBody: 'Data wordt wekelijks geüpdatet via geautomatiseerde scripts.',
    updateStatusLink: 'Bekijk gedetailleerde update status op de Data pagina',
    termsTitle: 'Gebruiksvoorwaarden',
    termsBody:
      'Dit project is bedoeld voor onderzoek, educatie en niet-commercieel gebruik. Respecteer de individuele gebruiksvoorwaarden van de API providers.',
    policiesTitle: 'API Provider Policies',
    methodNotes: {
      'Publieke API': "Publieke API's voor consumentengebruik. Respecteer rate limits en gebruiksvoorwaarden.",
      'Web scraping': 'Data verzameld via publiek toegankelijke websites. Niet geschikt voor high-frequency scraping.',
      'Browser-automatisering': 'Data verzameld via browser-automatisering. Gecached en wekelijks bijgewerkt.',
    } satisfies Record<SourceMethod, string>,
    policyGeneralLabel: 'Algemeen:',
    policyGeneralBody: 'Geen geautomatiseerde hoge-frequentie verzoeken. Gebruik cached data waar mogelijk.',
    attributionTitle: 'Vereiste Attributie',
    attributionIntro: 'Bij gebruik of redistributie van dit project:',
    attributionSources: 'Data bronnen:',
    attributionBoundaries: 'Gemeentegrenzen © OpenStreetMap contributors',
    disclaimerTitle: 'Disclaimer',
    disclaimerBody:
      'Dit project wordt geleverd "as is" zonder garantie. Data is verzameld van publieke bronnen en kan onnauwkeurigheden bevatten. Verifieer locatiegegevens bij de vervoerders. Dit project is niet gelieerd aan de databronbedrijven.',
    moreInfoTitle: 'Meer Informatie',
    moreInfoBody: 'Voor technische documentatie en uitgebreide details:',
    externalTitle: 'Externe Bronnen',
    externalIntro: 'Relevante externe bronnen en rapporten over pakketlogistiek.',
    open: 'Openen',
    study1Body:
      'Wetenschappelijke studie over de CO₂-impact van afhaalpunten in last-mile pakketbezorging. Analyseert hoe pakketpunten en pakketkluizen bijdragen aan duurzamere stadslogistiek vergeleken met traditionele thuisbezorging.',
    study1Link: 'Lees Artikel (ScienceDirect)',
    study1Meta: 'Renewable and Sustainable Energy Reviews | Augustus 2023',
    study2Body:
      'Studie naar consumentenadoptie van pakketkluizen in opkomende economieën (case study: Medellín, Colombia). Belangrijkste bevindingen: gemak en leversnelheid zijn de sterkste drivers; innovatieve en milieubewuste consumenten adopteren sneller. Opvallend: hoewel respondenten zichzelf als milieubewust beschouwen, zien ze geen sterke link tussen pakketkluizen en milieuvoordelen — dit wijst op een kenniskloof.',
    study2Link: 'Lees Artikel (Open Access)',
    study2Meta: 'Transportation Research Interdisciplinary Perspectives | Januari 2026',
  },

  overview: {
    subtitle: 'Marktaandeel en groei per vervoerder',
    totalTitle: 'Totaal Overzicht Pakketpunten',
    providerSubtitle: 'Historische ontwikkeling pakketpunten',
    totalPoints: 'Totaal pakketpunten',
    currentCount: 'Huidige stand',
    since: (week: string) => `Sinds ${week}`,
    totalGrowth: 'Totale groei',
    growthPercentage: 'Groei percentage',
    carriers: 'Vervoerders',
    marketShare: 'Marktaandeel',
    marketShareTitle: 'Marktaandeel per vervoerder',
    growthTitle: 'Groei per vervoerder',
    allCarriersOverTime: 'Ontwikkeling alle vervoerders over tijd',
    pointsOverTime: 'Aantal pakketpunten over tijd',
    insufficientData: 'Onvoldoende historische data beschikbaar om grafiek te tonen',
    weeklyChangeTitle: 'Wekelijkse verandering per vervoerder',
    weeklyChange: 'Wekelijkse verandering',
    change: 'Verandering',
    weeklyTableTitle: 'Wekelijkse data per vervoerder',
    weeklyData: 'Wekelijkse data',
    week: 'Week',
    weekLabel: (label: string) => `Week ${label}`,
    period: 'Periode',
    total: 'Totaal',
    difference: 'Verschil',
  },

  dataExport: {
    layoutTitle: 'Pakketpunten - Data',
    layoutSubtitle: 'Download pakketpunten data, bekijk statistieken en update status',
    backToMap: 'Terug naar kaart',
    tabDownloads: 'Downloads',
    tabMatrix: 'Data Matrix',
    tabStatistics: 'Statistieken',
    tabUpdates: 'Updates',
    tooManyDownloads: 'Te veel downloads. Probeer later opnieuw (max 5 downloads per uur).',
    downloadFailed: (status: string) => `Download mislukt: ${status}`,
    downloadStarted: 'Download gestart!',
    errorPrefix: 'Error:',
    unknownError: 'Onbekende fout',
    nationalTitle: 'Landelijke Data',
    allResidents: (population: string) => `Alle ${population} inwoners`,
    sumOfMunicipalities: (count: number) => `Som van alle ${count} gemeentes met boundary filtering`,
    pointsCount: (count: string) => `${count} pakketpunten`,
    municipalityTitle: 'Gemeente Data',
    searchPlaceholder: 'Zoek gemeente...',
    residents: (population: string) => `${population} inwoners`,
    downloadJson: 'Download JSON',
    downloadCsv: 'Download CSV',
    limitTitle: 'Download Limiet',
    limitBefore: 'Om misbruik te voorkomen is er een limiet van ',
    limitStrong: '5 downloads per uur',
    limitAfter: ' per IP-adres. Downloads worden geteld over alle bestanden heen.',
  },

  matrix: {
    overviewTitle: 'Overzicht',
    lastUpdate: (date: string) => `Laatste update: ${date}`,
    locations: 'Locaties',
    totalPoints: 'Totaal Pakketpunten',
    trendWeekLabel: 'week',
    trendTotalLabel: 'totaal',
    trendSummary: (weeks: number, since: string) => `Trend over ${weeks} weken (sinds ${since})`,
    tableTitle: 'Pakketpunten per Gemeente en Vervoerder',
    tableHint: 'Klik op een gemeente of vervoerder voor historische ontwikkeling en grafieken',
    colMunicipality: 'Gemeente',
    dashboard: 'Dashboard',
    dashboardFor: (name: string) => `Dashboard ${name}`,
    total: 'Totaal',
    trend: 'Trend',
    nationalTag: '(Landelijk)',
    totalRow: 'TOTAAL',
    legendTitle: 'Leeswijzer',
    legendNational: 'Landelijk overzicht (exacte som van alle gemeentes met boundary filtering)',
    legendRowsTitle: 'Klikbare rijen',
    legendRows: 'Klik op een gemeente voor historische data en trends',
    legendTotal: 'Klik voor marktaandeel en groei van alle vervoerders',
    legendCarriersTitle: 'Klikbare vervoerders',
    legendCarriers: 'Klik op een vervoerdernaam voor historische data en grafieken',
    legendTrend: 'Verandering ten opzichte van vorige week',
    legendDash: 'Geen pakketpunten van deze vervoerder in gemeente',
  },

  statistics: {
    metaTitle: `Statistieken — ${COUNTRY.siteName}`,
    metaDescription:
      'Marktaandeel en groei per vervoerder over tijd, per vervoerder te bekijken, plus pakketpunten per gemeente: dichtheid per inwoner en km² en de dekkingsgraad binnen 300, 400 en 500 meter.',
    noStatistics: 'Nog geen statistieken beschikbaar. Draai',
    noSnapshots: 'Nog geen historische snapshots. Draai',
    noData: 'Geen data.',
    withinRadius: (radius: string) => `binnen ${radius} m`,
    allCarriers: 'Alle vervoerders',
    chooseCarrier: 'Kies een vervoerder',
    chooseMunicipality: 'Kies een gemeente',
    wholeCountry: `Heel ${COUNTRY.nationalShortLabel}`,
    coverageDensityTitle: (place: string) => `Dekking en dichtheid — ${place}`,
    municipalityMeta: (region: string, population: string, area: string) =>
      `${region} · ${population} inwoners · ${area} km²`,
    nationalMeta: (count: string, date: string) => `${count} gemeenten · bijgewerkt ${date}`,
    per10kResidents: 'Per 10.000 inwoners',
    uniqueLocations: (n: string) => `op ${n} unieke locaties (vervoerders delen punten)`,
    perKm2: 'Per km²',
    coverageWithin500: 'Dekking binnen 500 m',
    ofLandArea: 'van het landoppervlak',
    perCarrier: 'Per vervoerder',
    perLocationType: 'Per type locatie',
    coverageRate: 'Dekkingsgraad',
    coverageExplanation:
      `Aandeel van het landoppervlak binnen loopafstand van een pakketpunt. Berekend in ${COUNTRY.metricCrsLabel}, dus in echte meters.`,
    developmentOf: (name: string) => `Ontwikkeling ${name}`,
    developmentSubtitle: 'Marktaandeel en groei per vervoerder, week op week',
    historyLoading: 'Historie laden...',
    noWeeklyHistory: (name: string) => `Nog geen wekelijkse historie voor ${name}.`,
    densityTitle: 'Gemeenten op dichtheid',
    searchPlaceholder: `Zoek gemeente of ${COUNTRY.regionLabel}...`,
    colMunicipality: 'Gemeente',
    colPoints: 'Punten',
    colPer10k: 'Per 10.000',
    colCoverage500: 'Dekking 500 m',
    noMatch: 'Geen gemeente gevonden.',
  },

  updates: {
    loading: 'Laden van update status...',
    unavailableTitle: 'Update status niet beschikbaar',
    unavailableBody: 'Kon de update status niet ophalen. Probeer later opnieuw.',
    title: 'Update Status',
    intro: 'Data wordt wekelijks geüpdatet via geautomatiseerde GitHub Actions scripts.',
    lastUpdate: 'Laatste update:',
    overview: 'Overzicht',
    allMunicipalitiesUpdated: 'Alle gemeenten bijgewerkt',
    municipalitiesFailed: (count: number) => `${count} gemeente(n) mislukt`,
    municipalities: 'Gemeenten',
    successful: 'Succesvol',
    failed: 'Mislukt',
    sourcesTitle: 'Databronnen',
    sourcesIntro: (staleAfterDays: number) =>
      `Wanneer de landelijke dataset van elke vervoerder voor het laatst is opgehaald. Een datum ouder dan ${staleAfterDays} dagen betekent dat de wekelijkse ophaalronde voor die vervoerder niet doorkwam.`,
    staleTooltip: (days: number) =>
      `Niet bijgewerkt in ${days} dagen — de laatste ophaalronde is geblokkeerd of mislukt.`,
    daysOld: (days: number) => ` · ${days} dagen oud`,
    fetchedPerMunicipality: 'geen landelijke cache',
    perCarrierTitle: 'Status per vervoerder',
    partiallyUpdated: (updated: number, total: number) => `${updated}/${total} gemeenten bijgewerkt`,
    failedParen: (count: number) => ` (${count} mislukt)`,
    allUpdated: (count: number) => `Alle ${count} gemeenten bijgewerkt`,
    points: 'punten',
    coverage: 'Dekking',
    logsTitle: 'Volledige Logs',
    logsBody:
      'Bekijk de volledige output van de laatste GitHub Actions workflow voor gedetailleerde informatie over eventuele fouten.',
    logsLink: 'Bekijk GitHub Actions Logs',
  },

  embed: {
    attribution: (name: string) => `${name} — Pakketpunten`,
    openInViewer: `Open op ${COUNTRY.siteName}`,
  },
} as const;

/** Widens every literal to `string`, keeping the shape and function parameters. */
type DeepString<T> = T extends (...args: infer A) => unknown
  ? (...args: A) => string
  : T extends string
    ? string
    : { [K in keyof T]: DeepString<T[K]> };

export type Strings = DeepString<typeof nl>;

const it: Strings = {
  common: {
    loading: 'Caricamento...',
    mapLoading: 'Caricamento mappa...',
    municipalityLoading: 'Caricamento comune...',
    close: 'Chiudi',
    unknown: 'Sconosciuto',
    unknownLower: 'sconosciuto',
    points: 'Punti di ritiro',
    updated: (date) => `Aggiornato: ${date}`,
  },

  meta: {
    title: `${COUNTRY.siteName} - Tutti i punti di ritiro in ${COUNTRY.name} sulla mappa`,
    description: (carriers) =>
      `Visualizza e confronta tutti i punti di ritiro e i locker in ${COUNTRY.name}. ${carriers} su una mappa interattiva per comune.`,
    ogTitle: `${COUNTRY.siteName} - Tutti i punti di ritiro in ${COUNTRY.name}`,
    ogDescription: (carrierCount) =>
      `Visualizza e confronta tutti i punti di ritiro e i locker in ${COUNTRY.name} di ${carrierCount} corrieri su una mappa interattiva per comune.`,
  },

  categories: {
    locker: 'Locker',
    shop: 'Punto di ritiro',
  },

  days: {
    long: {
      ma: 'Lunedì',
      di: 'Martedì',
      wo: 'Mercoledì',
      do: 'Giovedì',
      vr: 'Venerdì',
      za: 'Sabato',
      zo: 'Domenica',
    },
    short: {
      ma: 'Lun',
      di: 'Mar',
      wo: 'Mer',
      do: 'Gio',
      vr: 'Ven',
      za: 'Sab',
      zo: 'Dom',
    },
  },

  header: {
    appTitle: 'Punti di ritiro',
    nearestTitle: 'Cerca i punti di ritiro più vicini',
    nearestTitleWithAddress: (address) => `Punti di ritiro più vicini a "${address}"`,
    data: 'Dati',
    api: 'API',
    share: 'Condividi',
    about: 'Info',
    openMenu: 'Apri menu',
    findNearest: 'Cerca i più vicini',
    apiDocs: 'Documentazione API',
    shareEmbed: 'Condividi / Incorpora',
    aboutProject: 'Informazioni sul progetto',
    sidebarTitle: 'Filtri e statistiche',
    openFilters: 'Apri filtri',
    dataSourcesInfo: 'Informazioni sulle fonti dei dati',
  },

  filters: {
    title: 'Filtri',
    carriers: 'Corrieri',
    locationType: 'Tipo di punto',
    service: 'Servizio',
    pickup: 'Ritiro',
    pickupDescription: 'Ritirare un pacco',
    dropoff: 'Spedizione',
    dropoffDescription: 'Spedire un pacco',
    serviceHint: 'Ritiro = ricevere un pacco, Spedizione = spedire un pacco',
    locations: 'Punti',
    allLocations: 'Tutti i punti',
    sharedAddresses: 'Indirizzi condivisi',
    sharedAddressesHint: 'Indirizzi con più corrieri',
    markerStyle: 'Stile dei marcatori',
    logoIcons: 'Icone con logo',
    coloredDots: 'Punti colorati',
    coverage: 'Aree di copertura',
    buffer300: 'Linea buffer 300 m',
    buffer400: 'Linea buffer 400 m',
    bufferFill: 'Riempimento buffer',
    mergedBuffers: 'Buffer uniti',
    mergedBuffersTip: 'Se il caricamento dei punti di ritiro è lento, disattiva questa opzione.',
    boundary: 'Confine comunale',
    loadingProgress: (loaded, total) => `Caricamento: ${loaded}/${total}`,
    loadingParen: '(caricamento...)',
    reset: 'Reimposta filtri',
  },

  stats: {
    municipalitiesCount: (count) => `${count} comuni`,
    points: 'Punti di ritiro',
    occupancy: 'Occupazione',
  },

  map: {
    noPointsTitle: 'Nessun punto di ritiro trovato',
    noPointsBody: 'Questo comune al momento non ha punti di ritiro nel nostro database. La mappa mostra comunque il confine comunale.',
  },

  popup: {
    openingHours: 'Orari di apertura:',
    closed: 'chiuso',
    carrier: 'Corriere:',
    type: 'Tipo:',
    services: 'Servizi:',
    pickup: '↓ Ritiro',
    dropoff: '↑ Spedizione',
    showRawData: 'Mostra dati grezzi',
    streetView: 'Apri in Street View',
    searchLocation: 'Posizione cercata',
  },

  nearest: {
    title: 'Punti di ritiro più vicini',
    placeholder: 'Indirizzo o CAP...',
    locating: 'Rilevamento posizione…',
    useMyLocation: 'Usa la mia posizione',
    myLocation: 'La mia posizione',
    openingHours: 'Orari di apertura',
    modeAll: 'Tutti',
    modeNow: 'Aperti ora',
    modeCustom: 'A un orario',
    includeUnknownHours: 'Mostra anche i punti senza orari noti',
    noneWithinRadius: 'Nessun punto di ritiro trovato entro 500 m',
    noneOpenWithinRadius: 'Nessun punto di ritiro entro 500 m aperto a quest’ora',
    closedCount: (count) => `${count} chiusi`,
    withoutHoursCount: (count) => `${count} senza orari`,
    withoutHoursExcluded: (count) => `${count} senza orari esclusi`,
    resultsWithinRadius: (count) =>
      count === 1 ? '1 punto di ritiro entro 500 m' : `${count} punti di ritiro entro 500 m`,
    nowOpenSuffix: ' · aperti ora',
    openAtSuffix: (day, time) => ` · aperti ${day} alle ${time}`,
    helpText:
      'Inserisci un indirizzo o un CAP. La mappa passa automaticamente al comune giusto e mostra i 10 punti di ritiro più vicini.',
    searchFailed: 'Ricerca dell’indirizzo non riuscita',
    lookupFailed: 'Recupero dell’indirizzo non riuscito',
    addressOutsideCountry: `Questo indirizzo non si trova in un comune in ${COUNTRY.name}`,
    noCoordinates: 'Coordinate non disponibili',
    municipalityNotInDb: (name) => `Comune "${name}" non presente nel database`,
    noResults: 'Nessun risultato trovato',
    geolocationUnsupported: 'La geolocalizzazione non è supportata da questo browser',
    noMunicipalityAtLocation: `Nessun comune in ${COUNTRY.name} trovato in questa posizione`,
    reverseGeocodeFailed: 'Impossibile convertire la posizione in un indirizzo',
    permissionDenied: 'Posizione negata. Attiva l’accesso alla posizione per questo sito.',
    positionUnavailable: 'La posizione non è disponibile al momento',
    timeout: 'Il rilevamento della posizione ha richiesto troppo tempo',
    locateFailed: 'Rilevamento della posizione non riuscito',
  },

  search: {
    placeholder: 'Cerca indirizzo...',
    searchFailed: 'Ricerca dell’indirizzo non riuscita. Riprova.',
    lookupFailed: 'Recupero dell’indirizzo non riuscito. Riprova.',
    addressOutsideCountry: `Questo indirizzo non si trova in un comune in ${COUNTRY.name}`,
    noCoordinates: 'Coordinate non disponibili per questo indirizzo',
    municipalityNotAvailable: (name) => `Comune "${name}" non disponibile nel database`,
    noResultsFor: (query) => `Nessun risultato per "${query}"`,
    typeAddress: 'Indirizzo',
    typeStreet: 'Via',
    typePostcode: 'CAP',
    typePlace: 'Località',
  },

  selector: {
    placeholder: 'Seleziona comune...',
    count: (count) => `${count} comuni`,
    sortAsc: 'Ordina A-Z',
    sortDesc: 'Ordina Z-A',
    noMatches: (term) => `Nessun comune trovato per "${term}"`,
    nationalOverview: 'Panoramica nazionale',
  },

  share: {
    title: 'Condividi',
    directLink: (name) => `Link diretto a ${name}`,
    copy: 'Copia',
    copied: 'Copiato!',
    embedCode: 'Codice di incorporamento',
    embedHint: (name) => `Incolla questo codice nel tuo sito per incorporare la mappa di ${name}.`,
    width: 'Larghezza',
    height: 'Altezza',
    preview: 'Anteprima',
    iframeTitle: (name) => `Punti di ritiro ${name}`,
  },

  about: {
    title: 'Informazioni sul progetto',
    tabAbout: 'Info',
    tabSources: 'Fonti',
    tabUsage: 'Utilizzo',
    tabLinks: 'Link',
    intro: `Una piattaforma di visualizzazione interattiva dei punti di ritiro pacchi in ${COUNTRY.name}. Il progetto raccoglie dati pubblici di più corrieri e li mostra su una mappa chiara, con filtri e statistiche.`,
    audience:
      'Il visualizzatore aiuta comuni, ricercatori e decisori pubblici ad analizzare la copertura dei punti di ritiro sul territorio comunale e a individuare le aree poco servite, così da favorire l’apertura di nuovi punti di ritiro.',
    featuresTitle: 'Funzionalità',
    featureMap: `Mappa interattiva con tutti i comuni in ${COUNTRY.name}`,
    featureFiltering: 'Filtri in tempo reale per corriere e punto',
    featureCoverage: 'Visualizzazione delle aree di copertura (buffer da 300 m e 400 m)',
    featureStats: 'Statistiche per comune e per corriere',
    featureResponsive: 'Design responsive per desktop e mobile',
    featureExport: 'Esportazione dei dati per l’analisi',
    ackTitle: 'Ringraziamenti',
    ackDerivedFrom: 'Questo visualizzatore deriva da',
    ackJoin: ' e ',
    ackMiddle: ', nato come idea e in collaborazione con il ',
    ackOrg: 'Comune di Zwolle',
    ackEnd: ', che ringraziamo!',
    openSourceTitle: 'Open source',
    openSourceBody:
      'Questo progetto è open source e disponibile con licenza MIT. Per documentazione tecnica, codice sorgente e possibilità di contribuire:',
    githubRepo: 'Repository GitHub',
    sourcesTitle: 'Fonti dei dati',
    sourcesIntro:
      'I dati sulle posizioni sono raccolti dalle API pubbliche e dai siti web dei rispettivi corrieri, senza bisogno di autenticazione.',
    methods: {
      'Publieke API': 'API pubblica',
      'Web scraping': 'Web scraping',
      'Browser-automatisering': 'Automazione del browser',
    },
    missingTitle: 'Non inclusi (del tutto)',
    missingIntro: `Queste reti in ${COUNTRY.name} sono difficili o impossibili da ottenere senza un account o una chiave:`,
    additionalSourcesTitle: 'Altre fonti',
    addressSearchLabel: 'Ricerca indirizzi:',
    boundariesLabel: 'Confini comunali:',
    boundariesSource: `OpenStreetMap (codici ${COUNTRY.municipalityCodeLabel})`,
    basemapLabel: 'Mappa di base:',
    basemapSource: 'Tile di OpenStreetMap',
    updateFrequencyTitle: 'Frequenza di aggiornamento',
    updateFrequencyBody: 'I dati vengono aggiornati ogni settimana tramite script automatici.',
    updateStatusLink: 'Vedi lo stato dettagliato degli aggiornamenti nella pagina Dati',
    termsTitle: 'Condizioni d’uso',
    termsBody:
      'Questo progetto è destinato a ricerca, istruzione e uso non commerciale. Rispetta le condizioni d’uso dei singoli fornitori delle API.',
    policiesTitle: 'Condizioni dei fornitori di API',
    methodNotes: {
      'Publieke API': 'API pubbliche per uso da parte dei consumatori. Rispetta i limiti di frequenza e le condizioni d’uso.',
      'Web scraping': 'Dati raccolti da siti web accessibili pubblicamente. Non adatto allo scraping ad alta frequenza.',
      'Browser-automatisering': 'Dati raccolti tramite automazione del browser. Memorizzati in cache e aggiornati ogni settimana.',
    },
    policyGeneralLabel: 'In generale:',
    policyGeneralBody: 'Nessuna richiesta automatica ad alta frequenza. Usa i dati in cache quando possibile.',
    attributionTitle: 'Attribuzione richiesta',
    attributionIntro: 'In caso di uso o ridistribuzione di questo progetto:',
    attributionSources: 'Fonti dei dati:',
    attributionBoundaries: 'Confini comunali © OpenStreetMap contributors',
    disclaimerTitle: 'Esclusione di responsabilità',
    disclaimerBody:
      'Questo progetto è fornito "così com’è", senza alcuna garanzia. I dati provengono da fonti pubbliche e possono contenere imprecisioni. Verifica i dati sulle posizioni presso i corrieri. Questo progetto non è affiliato alle aziende che forniscono i dati.',
    moreInfoTitle: 'Maggiori informazioni',
    moreInfoBody: 'Per documentazione tecnica e dettagli approfonditi:',
    externalTitle: 'Fonti esterne',
    externalIntro: 'Fonti esterne e rapporti rilevanti sulla logistica dei pacchi.',
    open: 'Apri',
    study1Body:
      'Studio scientifico sull’impatto in termini di CO₂ dei punti di ritiro nella consegna dell’ultimo miglio. Analizza come punti di ritiro e locker contribuiscono a una logistica urbana più sostenibile rispetto alla tradizionale consegna a domicilio.',
    study1Link: 'Leggi l’articolo (ScienceDirect)',
    study1Meta: 'Renewable and Sustainable Energy Reviews | Agosto 2023',
    study2Body:
      'Studio sull’adozione dei locker da parte dei consumatori nelle economie emergenti (caso di studio: Medellín, Colombia). Risultati principali: comodità e velocità di consegna sono i fattori più forti; i consumatori innovativi e attenti all’ambiente li adottano più rapidamente. Da notare: pur considerandosi attenti all’ambiente, gli intervistati non vedono un legame forte tra locker e benefici ambientali, il che indica una lacuna di conoscenza.',
    study2Link: 'Leggi l’articolo (Open Access)',
    study2Meta: 'Transportation Research Interdisciplinary Perspectives | Gennaio 2026',
  },

  overview: {
    subtitle: 'Quota di mercato e crescita per corriere',
    totalTitle: 'Panoramica totale dei punti di ritiro',
    providerSubtitle: 'Andamento storico dei punti di ritiro',
    totalPoints: 'Punti di ritiro totali',
    currentCount: 'Situazione attuale',
    since: (week) => `Da ${week}`,
    totalGrowth: 'Crescita totale',
    growthPercentage: 'Crescita percentuale',
    carriers: 'Corrieri',
    marketShare: 'Quota di mercato',
    marketShareTitle: 'Quota di mercato per corriere',
    growthTitle: 'Crescita per corriere',
    allCarriersOverTime: 'Andamento di tutti i corrieri nel tempo',
    pointsOverTime: 'Numero di punti di ritiro nel tempo',
    insufficientData: 'Dati storici insufficienti per mostrare il grafico',
    weeklyChangeTitle: 'Variazione settimanale per corriere',
    weeklyChange: 'Variazione settimanale',
    change: 'Variazione',
    weeklyTableTitle: 'Dati settimanali per corriere',
    weeklyData: 'Dati settimanali',
    week: 'Settimana',
    weekLabel: (label) => `Settimana ${label}`,
    period: 'Periodo',
    total: 'Totale',
    difference: 'Differenza',
  },

  dataExport: {
    layoutTitle: 'Punti di ritiro - Dati',
    layoutSubtitle: 'Scarica i dati dei punti di ritiro, consulta statistiche e stato degli aggiornamenti',
    backToMap: 'Torna alla mappa',
    tabDownloads: 'Download',
    tabMatrix: 'Matrice dati',
    tabStatistics: 'Statistiche',
    tabUpdates: 'Aggiornamenti',
    tooManyDownloads: 'Troppi download. Riprova più tardi (max 5 download all’ora).',
    downloadFailed: (status) => `Download non riuscito: ${status}`,
    downloadStarted: 'Download avviato!',
    errorPrefix: 'Errore:',
    unknownError: 'Errore sconosciuto',
    nationalTitle: 'Dati nazionali',
    allResidents: (population) => `Tutti i ${population} abitanti`,
    sumOfMunicipalities: (count) => `Somma di tutti i ${count} comuni con filtro sui confini`,
    pointsCount: (count) => `${count} punti di ritiro`,
    municipalityTitle: 'Dati per comune',
    searchPlaceholder: 'Cerca comune...',
    residents: (population) => `${population} abitanti`,
    downloadJson: 'Scarica JSON',
    downloadCsv: 'Scarica CSV',
    limitTitle: 'Limite di download',
    limitBefore: 'Per evitare abusi è previsto un limite di ',
    limitStrong: '5 download all’ora',
    limitAfter: ' per indirizzo IP. I download vengono conteggiati su tutti i file.',
  },

  matrix: {
    overviewTitle: 'Panoramica',
    lastUpdate: (date) => `Ultimo aggiornamento: ${date}`,
    locations: 'Località',
    totalPoints: 'Punti di ritiro totali',
    trendWeekLabel: 'settimana',
    trendTotalLabel: 'totale',
    trendSummary: (weeks, since) => `Andamento su ${weeks} settimane (da ${since})`,
    tableTitle: 'Punti di ritiro per comune e corriere',
    tableHint: 'Clicca su un comune o un corriere per andamento storico e grafici',
    colMunicipality: 'Comune',
    dashboard: 'Dashboard',
    dashboardFor: (name) => `Dashboard ${name}`,
    total: 'Totale',
    trend: 'Andamento',
    nationalTag: '(Nazionale)',
    totalRow: 'TOTALE',
    legendTitle: 'Legenda',
    legendNational: 'Panoramica nazionale (somma esatta di tutti i comuni con filtro sui confini)',
    legendRowsTitle: 'Righe cliccabili',
    legendRows: 'Clicca su un comune per dati storici e andamento',
    legendTotal: 'Clicca per quota di mercato e crescita di tutti i corrieri',
    legendCarriersTitle: 'Corrieri cliccabili',
    legendCarriers: 'Clicca sul nome di un corriere per dati storici e grafici',
    legendTrend: 'Variazione rispetto alla settimana precedente',
    legendDash: 'Nessun punto di ritiro di questo corriere nel comune',
  },

  statistics: {
    metaTitle: `Statistiche — ${COUNTRY.siteName}`,
    metaDescription:
      'Quota di mercato e crescita per corriere nel tempo, consultabili per singolo corriere, più i punti di ritiro per comune: densità per abitante e per km² e copertura entro 300, 400 e 500 metri.',
    noStatistics: 'Nessuna statistica ancora disponibile. Esegui',
    noSnapshots: 'Nessuno snapshot storico ancora disponibile. Esegui',
    noData: 'Nessun dato.',
    withinRadius: (radius) => `entro ${radius} m`,
    allCarriers: 'Tutti i corrieri',
    chooseCarrier: 'Scegli un corriere',
    chooseMunicipality: 'Scegli un comune',
    wholeCountry: `Tutta ${COUNTRY.nationalShortLabel}`,
    coverageDensityTitle: (place) => `Copertura e densità — ${place}`,
    municipalityMeta: (region, population, area) => `${region} · ${population} abitanti · ${area} km²`,
    nationalMeta: (count, date) => `${count} comuni · aggiornato il ${date}`,
    per10kResidents: 'Ogni 10.000 abitanti',
    uniqueLocations: (n) => `in ${n} sedi distinte (i corrieri condividono i punti)`,
    perKm2: 'Per km²',
    coverageWithin500: 'Copertura entro 500 m',
    ofLandArea: 'della superficie terrestre',
    perCarrier: 'Per corriere',
    perLocationType: 'Per tipo di punto',
    coverageRate: 'Grado di copertura',
    coverageExplanation:
      `Quota della superficie terrestre a distanza pedonale da un punto di ritiro. Calcolata in ${COUNTRY.metricCrsLabel}, quindi in metri reali.`,
    developmentOf: (name) => `Andamento ${name}`,
    developmentSubtitle: 'Quota di mercato e crescita per corriere, settimana per settimana',
    historyLoading: 'Caricamento dello storico...',
    noWeeklyHistory: (name) => `Nessuno storico settimanale ancora disponibile per ${name}.`,
    densityTitle: 'Comuni per densità',
    searchPlaceholder: `Cerca comune o ${COUNTRY.regionLabel}...`,
    colMunicipality: 'Comune',
    colPoints: 'Punti',
    colPer10k: 'Ogni 10.000',
    colCoverage500: 'Copertura 500 m',
    noMatch: 'Nessun comune trovato.',
  },

  updates: {
    loading: 'Caricamento dello stato degli aggiornamenti...',
    unavailableTitle: 'Stato degli aggiornamenti non disponibile',
    unavailableBody: 'Impossibile recuperare lo stato degli aggiornamenti. Riprova più tardi.',
    title: 'Stato degli aggiornamenti',
    intro: 'I dati vengono aggiornati ogni settimana tramite script automatici su GitHub Actions.',
    lastUpdate: 'Ultimo aggiornamento:',
    overview: 'Panoramica',
    allMunicipalitiesUpdated: 'Tutti i comuni aggiornati',
    municipalitiesFailed: (count) => (count === 1 ? '1 comune non riuscito' : `${count} comuni non riusciti`),
    municipalities: 'Comuni',
    successful: 'Riusciti',
    failed: 'Non riusciti',
    sourcesTitle: 'Fonti dei dati',
    sourcesIntro: (staleAfterDays) =>
      `Quando il dataset nazionale di ciascun corriere è stato scaricato l’ultima volta. Una data più vecchia di ${staleAfterDays} giorni significa che lo scaricamento settimanale per quel corriere non è andato a buon fine.`,
    staleTooltip: (days) =>
      `Non aggiornato da ${days} giorni: l’ultimo scaricamento è stato bloccato o non è riuscito.`,
    daysOld: (days) => ` · ${days} giorni fa`,
    fetchedPerMunicipality: 'nessuna cache nazionale',
    perCarrierTitle: 'Stato per corriere',
    partiallyUpdated: (updated, total) => `${updated}/${total} comuni aggiornati`,
    failedParen: (count) => ` (${count} non riusciti)`,
    allUpdated: (count) => `Tutti i ${count} comuni aggiornati`,
    points: 'punti',
    coverage: 'Copertura',
    logsTitle: 'Log completi',
    logsBody:
      'Consulta l’output completo dell’ultimo workflow di GitHub Actions per informazioni dettagliate su eventuali errori.',
    logsLink: 'Vedi i log di GitHub Actions',
  },

  embed: {
    attribution: (name) => `${name} — Punti di ritiro`,
    openInViewer: `Apri su ${COUNTRY.siteName}`,
  },
};

const DICTIONARIES: Record<'nl' | 'it', Strings> = { nl, it };

/** The UI strings for the active country's language. */
export const t: Strings = DICTIONARIES[COUNTRY.language];
